### ISSUE TITLE
"Fortnite was not started correctly" when injecting cobalt on latest  (26.00)

### ISSUE THREAD

**Issue by theconicaldepression** [Milxnor/Cobalt#4]
I think this is due to the Push Widget pattern being outdated, as i tried [PlataniumV2](https://github.com/FortniteModding/PlataniumV2) and when injected it says "third pattern outdated", i checked plataniumv2's code and the third pattern is push widget

**Comment by Zordon1337** [comment]
first of all don't use latest on private servers because afaik you WILL get hwid banned

**Comment by Milxnor** [comment]
> first of all don't use latest on private servers because afaik you WILL get hwid banned

i suppose he would know the consequences + dont spread rumors lmfao this is false

**Comment by Milxnor** [comment]
Resolved
