### ISSUE TITLE
what can i do with the season 13 is epic thing

### ISSUE THREAD

**Issue by nicdoesstuff** [Milxnor/Cobalt#9]

**Comment by nicdoesstuff** [comment]
![image](https://github.com/Milxnor/Cobalt/assets/155686133/2d3e69ff-96fe-42fc-833e-6486ae5227a2)

**Comment by Windermed** [comment]
I'm pretty sure this just enables you to log onto Epic's servers on v13.40 (since that version is still online) while using a hybrid server but it tricks the game into thinking your sending requests from an Apple Client so that it can let you log in.
